DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS soilmoisture;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE soilmoisture (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  region TEXT NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  interval_hours FLOAT[] NOT NULL,
  output_format TEXT NOT NULL
);
